defaults: &defaults
  app_name: "FB9"
  domain: "http://fbnai.dev"    
  admin_emails: 
    - "xuite.joke@gmail.com"
  google_analytics_key: ""
  default_logo_url: "/logo.png"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
